name: 'healthcare_analytics'
version: '1.0.0'
config-version: 2

profile: 'healthcare_analytics'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  healthcare_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: gold
